matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.2
    - os: osx
      dotnet: 2.2.107
language: csharp
solution: QuestSaberPatch.sln
mono: none
dotnet: 2.2
script:
  - dotnet publish -c Release -r "${TRAVIS_OS_NAME}-x64" --self-contained true /p:useapphost=true
  - python -m pip install pyinstaller
  - pyinstaller --onefile ./testdata/gui_script.py
after_success:
  - cp ./jsonApp/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64/publish/jsonApp* ./app/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64/publish/
  - cp ./jsonApp2/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64/publish/jsonApp2* ./app/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64/publish/
  - cp ./dist/gui_script* ./app/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64/publish/
  - cd app/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64
  - mv publish questsaberpatch
  - ls -lAhR questsaberpatch
  - zip -r questsaberpatch.zip questsaberpatch
  - ls -lAhR
  - wget --method PUT --body-file="questsaberpatch.zip" "https://transfer.sh/questsaberpatch-${TRAVIS_OS_NAME}.zip" -O - -nv

