image: Visual Studio 2017
clone_folder: c:\projects\QuestSaberPatch
before_build:
  - cd c:\projects\QuestSaberPatch
  - dotnet --version
build_script:
  - dotnet publish -c Release -r "win-x64" --self-contained true /p:useapphost=true
  - python -m pip install pyinstaller
  - pyinstaller --onefile ./testdata/gui_script.py
after_build:
  - dir /adh /s
  # I have no idea if Windows wildcards are zero or more or one or more so just drop the last letter
  - xcopy .\jsonApp\bin\Release\netcoreapp2.2\win-x64\publish\jsonAp* .\app\bin\Release\netcoreapp2.2\win-x64\publish
  - xcopy .\jsonApp2\bin\Release\netcoreapp2.2\win-x64\publish\jsonApp* .\app\bin\Release\netcoreapp2.2\win-x64\publish
  - xcopy .\testdata\dist\gui_script.exe .\app\bin\Release\netcoreapp2.2\win-x64\publish
  - md .\app\bin\Release\netcoreapp2.2\win-x64\questsaberpatch
  - move .\app\bin\Release\netcoreapp2.2\win-x64\publish .\app\bin\Release\netcoreapp2.2\win-x64\questsaberpatch
  - ren .\app\bin\Release\netcoreapp2.2\win-x64\questsaberpatch\publish questsaberpatch
artifacts:
  - path: .\app\bin\Release\netcoreapp2.2\win-x64\questsaberpatch
    type: zip
